# See PwnPlantGrowth's page on http://dev.bukkit.org for more config details.

# Full biome list available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html

# Plants / Crops are available in the "Material" list. See the following for official material names.
# Full material list available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# Which worlds should this plugin be enabled in? Worlds not in this list will have default growth.
enabled_worlds:
  - example_world
  - example_world_nether
  - example_world_end
  
# Natural sky light level: 0 allows any, 10 is sunlight through glass/tree leaves, 15 is direct sunlight
min_natural_light: 10

# List of items allowed to grow in false light (torches, lightstone, lava) - use offical MATERIAL names to add to this list
grow_in_dark: 
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - NETHER_WARTS
  - COCOA 

# Enable use of weed killer
weed_killer_enabled: false

# A Block that can act as a weed killer (keeps plants from dying, will NOT affect growth rates)
weed_killer: GOLD_BLOCK

# Radius that weed killer protects, plants within this distance of the weed killer block will not turn to dead shrubs
weed_killer_radius: 5

# Enable use of fertilizer
fertilizer_enabled: false

# A Block that can act as a fertilizer (keeps plants growing at 100% or rate set below - as long as they are in the right biome)
fertilizer: SOUL_SAND

# Radius that fertilizer affects, plants within this distance of the block will grow at 100% or rate set below
fertilizer_radius: 5

# Set the fertilizer rate of growth globally when a fertilizer block is nearby, defaults to 100% 
# note that specific plant/biome dark rates and death rates take effect regardless of fertilizer 
fertilizer_rate: 100

# Enable use of UV Light Block
uv_enabled: false

# A Block that can act as UV Light (will allow plants in radius to grow where there is no natural light, -note, still requires actual lighting)
uv: GLOWSTONE

# Radius that UV affects
uv_radius: 5

# Allow plugin to capture bonemeal
limit_bonemeal: false

# Show players possible growth rates for an item if they click it on a block in a biome
report_growth: false

# Message format - set how the plugin displays messages to users
msg_format: "&2PwnPlantGrowth: &r"

# Run various debug logs to view additional plugin data for troubleshooting and configuration. Can get spammy, use for debugging.
debug_log: false

# Will additionally log Tree Growing Events.
tree_log: false

# Will additionally log Plant Growing Events.
plant_log: false

# Will additionally log Bonemeal Growing Events.
bonemeal_log: false

# Set true if you want also to log the coordinates on the world of the event - gets really spammy
log_coords: false

# Ultra verbose logging, logs tons of information that may be useful for extra debugging
log_verbose: false

# BIOME GROUPS - You can MAKE YOUR OWN versions of these, this is just a sample set of groups
BiomeGroup:
    Hell:
    - BASALT_DELTAS
    - CRIMSON_FOREST
    - NETHER_WASTES
    - SOUL_SAND_VALLEY
    - WARPED_FOREST
    End:
    - END_BARRENS
    - END_HIGHLANDS
    - END_MIDLANDS
    - SMALL_END_ISLANDS
    - THE_END
    - THE_VOID
    Badlands:
    - BADLANDS
    - BADLANDS_PLATEAU
    - ERODED_BADLANDS
    - MODIFIED_BADLANDS_PLATEAU
    - MODIFIED_WOODED_BADLANDS_PLATEAU
    - WOODED_BADLANDS_PLATEAU
    Desert:
    - DESERT
    - DESERT_HILLS
    - DESERT_LAKES
    Jungle:
    - BAMBOO_JUNGLE
    - BAMBOO_JUNGLE_HILLS
    - JUNGLE
    - JUNGLE_EDGE
    - JUNGLE_HILLS
    - MODIFIED_JUNGLE
    - MODIFIED_JUNGLE_EDGE
    GreatGrowing:
    - BEACHES
    - BIRCH_FOREST
    - FOREST
    - JUNGLE
    - MUSHROOM_ISLAND
    - MUSHROOM_ISLAND_SHORE
    - PLAINS
    - RIVER
    - SAVANNA
    - SWAMPLAND
    GoodGrowing: 
    - BIRCH_FOREST_HILLS
    - FOREST_HILLS
    - JUNGLE_HILLS
    - MESA
    - ROOFED_FOREST
    - TAIGA
    - REDWOOD_TAIGA
    - REDWOOD_TAIGA_HILLS
    - TAIGA_HILLS
    BadGrowing:
    - COLD_BEACH
    - EXTREME_HILLS
    - EXTREME_HILLS_WITH_TREES
    - FROZEN_RIVER
    - ICE_FLATS
    - ICE_MOUNTAINS
    - MESA_CLEAR_ROCK
    - MESA_ROCK
    - SAVANNA_ROCK
    - STONE_BEACH
    - TAIGA_COLD
    - TAIGA_COLD_HILLS
    Snowy:
    - SNOWY_BEACH
    - SNOWY_MOUNTAINS
    - SNOWY_TAIGA
    - SNOWY_TAIGA_HILLS
    - SNOWY_TAIGA_MOUNTAINS
    - SNOWY_TUNDRA
    NoGrowing:
    - VOID
    - SKY

# Ageable / BlockGrowEvent or BlockSpreadEvent - Important note, as of PPG 1.6 the plant names are now all in UPPER CASE matching the actual Bukkit Material.TYPE 
BAMBOO:
    Growth: 50
    Death: 5
    BiomeGroup:
    - Jungle
    Jungle:
      Growth: 50
      GrowthDark: 25
      Death: 0 
      DeathDark: 5    
    Biome:
    - NONE

# Bamboo Sapling is a freshly planted bamboo, it is a block item not a tree item even though it is labeled "sapling"
BAMBOO_SAPLING:
    Growth: 50
    Death: 5
    BiomeGroup:
    - Jungle
    Jungle:
      Growth: 50
      GrowthDark: 25
      Death: 0 
      DeathDark: 5    
    Biome:
    - NONE
    
# In this example beetroot only grows in GoodGrowing and GreatGrowing biomes, setting biome NONE should block all others
BEETROOTS: 
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10  
    Biome:
    - NONE 

# In this example cactus is restricted to the biomegroup desert and savanna
CACTUS:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25
    BiomeGroup:
    - Desert
    Desert:
      Growth: 50
      GrowthDark: 25
      Death: 0 
      DeathDark: 5      
    Biome: 
    - SAVANNA
    SAVANNA:
      Growth: 25
      Death: 50

# Carrot example is setup like beetroot but also grows in desert by setting Biome: - DESERT value
CARROTS: 
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25    
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10      
    Biome: 
    - DESERT
    DESERT:
      Growth: 25
      Death: 50

# Chorus flower needs endstone to grow on and be in the end
CHORUS_FLOWER:
    Growth: 50
    Death: 5
    Biome: 
    - END_BARRENS
    - END_HIGHLANDS
    - END_MIDLANDS
    - THE_END
    
# In this example Cocoa will only grow in jungle biomes at 25% normal rate
COCOA: 
    Growth: 25
    Death: 5
    BiomeGroup:
    - Jungle
    Jungle:
      Growth: 25
      GrowthDark: 25
      Death: 5 
      DeathDark: 5    
    Biome:
    - NONE

# In this example grass, tallgrass, bonemeal used on grass - will grow anywhere - Biome: [] - but only at 50% 
GRASS: 
    Growth: 50
    Death: 0
    Biome: []

# Similar to GRASS above, specifically for when bonemeal is used on a grass block
GRASS_BLOCK: 
    Growth: 50
    Death: 0
    Biome: []
    
# In this example kelp will grow anywhere - Biome: [] - but only at 50%
KELP: 
    Growth: 50
    Death: 5
    Biome: []

# In this example melons will grow anywhere - Biome: [] - but only at 50%
MELON: 
    Growth: 50
    Death: 5
    Biome: []

# This is the stem portion, it can be set to grow differently than the melon/pumpkin
MELON_STEM:
    Growth: 50
    Death: 5
    Biome: []

# In this example netherwart is restricted to the nether biomegroup at 25%
NETHER_WART:
    Growth: 25
    Death: 5
    BiomeGroup: 
    - Hell
    Hell: 
      Growth: 25
      Death: 5
    Biome: []
            
# Potato will grow in great and good areas, all others at its default rate with Biome: []
POTATOES:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10
    Biome: []

PUMPKIN:
    Growth: 50
    Death: 5    
    Biome: []

# This is the stem portion, it can be set to grow differently than the melon/pumpkin
PUMPKIN_STEM:
    Growth: 50
    Death: 5
    Biome: []

# In this example sugar cane will only grow in these biomes at a 50% rate and no where else    
SUGAR_CANE:
    Growth: 50
    Death: 5
    Biome:
    - BEACHES
    - BEACH
    - RIVER
    - SWAMPLAND  

# Sweet berry bush was added in minecraft 1.14 and pwnplantgrowth v2.5.0
SWEET_BERRY_BUSH:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10
    Biome: []
    
TWISTING_VINES: 
    Growth: 25
    Death: 5
    BiomeGroup: 
    - Hell
    Hell: 
      Growth: 25
      Death: 5
    Biome: []
    
WEEPING_VINES:
    Growth: 25
    Death: 5
    BiomeGroup: 
    - Hell
    Hell: 
      Growth: 25
      Death: 5
    Biome: []
    
# This is WHEAT - In this example wheat will grow everywhere at 50% rate, and at better rates in great and good growing groups
WHEAT:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10
    Biome: []
    
      
# StructureGrowEvent Items
# As of version 2.4.0 PwnPlantGrowth switched to the block type (sapling) that starts the tree/structure, the growth result could be regular, tall, mega, etc based on other conditions.
ACACIA_SAPLING:
    Growth: 50
    Death: 5
    Biome:
    - SAVANNA
    - SAVANNA_MOUNTAINS
    - SAVANNA_PLATEAU
    - SAVANNA_PLATEAU_MOUNTAINS
    
BIRCH_SAPLING:
    Growth: 50
    Death: 5
    Biome:
    - FOREST
    - FOREST_HILLS
    - TAIGA
    - TAIGA_HILLS
    
DARK_OAK_SAPLING:
    Growth: 50
    Death: 5
    Biome:
    - ROOFED_FOREST        
    - ROOFED_FOREST_MOUNTAINS   
    
JUNGLE_SAPLING:
    Growth: 50
    Death: 5
    BiomeGroup:
    - Jungle
    Jungle:
      Growth: 50
      GrowthDark: 25
      Death: 0 
      DeathDark: 5    
    Biome:
    - NONE 
           
OAK_SAPLING:
    Growth: 50
    Death: 5
    Biome: []
    
SPRUCE_SAPLING:
    Growth: 50
    Death: 5
    Biome: [] 

BROWN_MUSHROOM:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
              
RED_MUSHROOM:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
    
CRIMSON_FUNGUS:
    Growth: 50
    Death: 5
    Biome:
    - CRIMSON_FOREST
              
WARPED_FUNGUS:
    Growth: 50
    Death: 5
    Biome:
    - WARPED_FOREST
                
# Plugin will check for the following list of plants as of ver. 2.6.1 for Minecraft 1.19.x

# Ageable / BlockGrowEvent: "BAMBOO", "BAMBOO_SAPLING", "BEETROOTS", "CACTUS", "CARROTS", "COCOA", "CHORUS_FLOWER", "GRASS", "GRASS_BLOCK", "KELP", "MELON", "MELON_STEM", "NETHER_WART", "POTATOS", "PUMPKIN", "PUMPKIN_STEM", "SUGAR_CANE", "TWISTING_VINES", "WEEPING_VINES", "WHEAT", "SWEET_BERRY_BUSH", "CAVE_VINES"
# Structures / StructureGrowEvent: "ACACIA_SAPLING", "BIRCH_SAPLING", "DARK_OAK_SAPLING", "JUNGLE_SAPLING", "OAK_SAPLING", "SPRUCE_SAPLING", "RED_MUSHROOM", "BROWN_MUSHROOM", "CRIMSON_FUNGUS", "WARPED_FUNGUS", "MANGROVE_PROPAGULE"
