main: com.pwn9.PwnPlantGrowth.PwnPlantGrowth
name: PwnPlantGrowth
version: 2.6.1
author: tremor77
description: Take control over all plant growth
website: http://pwn9.com
api-version: 1.19
commands:
   ppg:
      description: Execute a PwnPlantGrowth command
      usage: /ppg <reload|save>
      permission: ppg.ppg
      permission-message: You dont have permission for this command
permissions:
  ppg.*:
    description: gives all permissions of PwnPlantGrowth
    default: op
    children:
        ppg.ppg: true
        ppg.reload: true 
        ppg.save: true